#!/bin/sh

# Fail fast
set -e

# http://stackoverflow.com/a/246128/6740471
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMMON_FILES=".vimrc .tmux.conf"
MAC_FILES=".inputrc .bashrc .bash_profile"
OS=$(uname 2> /dev/null)
BACKUPDIR=$(mktemp -d "$HOME/dotfiles.bak.XXX")

[ "$OS" = "Darwin" ] && COMMON_FILES="$COMMON_FILES $MAC_FILES"

# Check if we have a running desktop environment. I am not sure this
# will work for bare window managers without a display manager.
# http://unix.stackexchange.com/a/116694
has_running_de() {
    if [ "$XDG_CURRENT_DESKTOP" = "" ]
    then
        desktop=$(echo "$XDG_DATA_DIRS" | sed 's/.*\(xfce\|kde\|gnome\).*/\1/')
    else
        desktop=$XDG_CURRENT_DESKTOP
    fi

    desktop=${desktop,,}  # convert to lower case
    if [ -z "$desktop" ]; then
        return 1
    fi
    return 0
}

backupfile() {
    cp -f $1 $BACKUPDIR
}

cleanup() {
    # Remove backup dir if it is empty
    if [ -z "$(ls -A $BACKUPDIR)" ]; then
        rm -fr $BACKUPDIR
    fi
}
trap cleanup EXIT

# Create symlinks to common rc files
for f in $COMMON_FILES; do
    target="$HOME/${f##*/}"

    # Remove target if it is a symlink, otherwise copy
    # it to the dotfiles.bak.XXX dir
    if [ -L "$target" ]; then
        rm -f $target
    else
        if [ -f "$target" ]; then
            backupfile $target
        fi
    fi

    ln -sf "$DIR/$f" ~/
done

# Setup i3 configuration files for Linux
if [ "$OS" = "Linux" ] && has_running_de; then
    i3confdir="$HOME/.config/i3"
    i3conf="$i3confdir/config"
    if [ ! -L "$i3conf" ] && [ -f "$i3conf" ]; then
        backupfile "$i3conf"
    fi
    mkdir -p "$i3confdir"
    ln -sf "$DIR/config" "$i3conf"
fi
